name: TestDriver.ai - Template

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    name: "TestDriver"
    runs-on: ubuntu-latest
    steps:
      - uses: dashcamio/testdriver@main
        id: testdriver
        with:
          version: v2.13.0
          key: <YOUR-KEY>
          prerun: | # make a random email address up
            echo "hello world"
          prompt: |
            1. Open Google Chrome